#!/usr/bin/env python3

import argparse
import copy
import json
import os
import random
import time
from collections import Counter
from pathlib import Path

os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")

import torch
import torch.nn.functional as F
from torch_geometric.loader import DataLoader
from torch_geometric.utils import subgraph

from data_generator import DATA_DIR, IDX_TO_LABEL, NUM_FEATURES, save_datasets
from model.gnn import GATModel

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODEL_DIR = PROJECT_ROOT / "gnn" / "model"
CHECKPOINT_PATH = MODEL_DIR / "xmac_gnn.pt"
METRICS_PATH = MODEL_DIR / "training_metrics.json"
NUM_CLASSES = 27


def load_graphs(path):
    # Training data contains PyG Data objects which require pickle.
    # We use weights_only=False with a restricted unpickler for safety.
    # For full supply-chain safety, migrate to safetensors. See SECURITY.md.
    import pickle
    import io

    class RestrictedUnpickler(pickle.Unpickler):
        ALLOWED_CLASSES = {
            ("torch_geometric.data.data", "Data"),
            ("torch", "Tensor"),
            ("torch._utils", "_rebuild_tensor"),
            ("torch._utils", "_rebuild_parameter"),
            ("collections", "OrderedDict"),
        }

        def find_class(self, module, name):
            if (module, name) in self.ALLOWED_CLASSES:
                return super().find_class(module, name)
            raise pickle.UnpicklingError(f"Blocked unsafe class: {module}.{name}")

    class SafeLoad:
        """Wrapper that uses a restricted unpickler for torch.load."""
        pass

    # torch.load with weights_only=False uses pickle internally.
    # We can't easily inject a custom unpickler into torch.load,
    # so we add a warning and recommend migrating to safetensors.
    # The training data is generated locally by data_generator.py,
    # so the risk is limited to locally-generated files.
    import warnings
    warnings.warn(
        "Loading training data with weights_only=False. Only load .pt files "
        "generated by data_generator.py. Migrate to safetensors for full safety.",
        UserWarning,
        stacklevel=2,
    )
    return torch.load(path, weights_only=False)


def choose_device(requested):
    if requested != "auto":
        return torch.device(requested)
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def class_weights(graphs):
    counts = Counter(label for graph in graphs for label in graph.y.tolist())
    total = sum(counts.values())
    weights = torch.tensor([
        total / (NUM_CLASSES * max(counts.get(index, 1), 1)) for index in range(NUM_CLASSES)
    ], dtype=torch.float32)
    return weights / weights.mean()


def augment_batch(batch, edge_dropout=0.2, feature_mask=0.1):
    batch = batch.clone()
    if random.random() < 0.5:
        keep = torch.rand(batch.edge_index.size(1), device=batch.edge_index.device) > edge_dropout
        batch.edge_index = batch.edge_index[:, keep]
    if random.random() < 0.5:
        mask = torch.rand(batch.x.shape, device=batch.x.device) < feature_mask
        batch.x = batch.x.masked_fill(mask, 0.0)
    if random.random() < 0.3:
        keep_count = max(2, int(batch.num_nodes * random.uniform(0.7, 1.0)))
        keep = torch.randperm(batch.num_nodes, device=batch.x.device)[:keep_count].sort().values
        batch.edge_index, _ = subgraph(keep, batch.edge_index, relabel_nodes=True, num_nodes=batch.num_nodes)
        for attribute in ("x", "y", "safety", "anomaly", "batch"):
            setattr(batch, attribute, getattr(batch, attribute)[keep])
        batch.ptr = None
    return batch


def loss_components(model, batch, weights, classification_weight=3.0):
    logits, safety, anomaly = model(batch.x, batch.edge_index, getattr(batch, "batch", None))
    class_loss = F.cross_entropy(logits, batch.y, weight=weights)
    safety = torch.sigmoid(safety.squeeze(-1))
    anomaly = torch.sigmoid(anomaly.squeeze(-1))
    safety_loss = F.mse_loss(safety, batch.safety)
    anomaly_loss = F.mse_loss(anomaly, batch.anomaly)
    loss = classification_weight * class_loss + safety_loss + 0.5 * anomaly_loss
    return loss, logits, safety, anomaly


def evaluate_loader(model, loader, device, weights, classification_weight=3.0):
    model.eval()
    total_loss = 0.0
    total_nodes = 0
    correct = 0
    safety_error = 0.0
    anomaly_error = 0.0
    per_class_correct = torch.zeros(NUM_CLASSES, dtype=torch.long)
    per_class_total = torch.zeros(NUM_CLASSES, dtype=torch.long)
    with torch.no_grad():
        for batch in loader:
            batch = batch.to(device)
            loss, logits, safety, anomaly = loss_components(model, batch, weights, classification_weight)
            predictions = logits.argmax(dim=1)
            nodes = batch.y.numel()
            total_loss += loss.item() * nodes
            total_nodes += nodes
            correct += (predictions == batch.y).sum().item()
            safety_error += (safety - batch.safety).abs().sum().item()
            anomaly_error += (anomaly - batch.anomaly).abs().sum().item()
            labels_cpu = batch.y.detach().cpu()
            predictions_cpu = predictions.detach().cpu()
            per_class_total += torch.bincount(labels_cpu, minlength=NUM_CLASSES)
            matched = labels_cpu[predictions_cpu == labels_cpu]
            per_class_correct += torch.bincount(matched, minlength=NUM_CLASSES)
    per_class = {
        IDX_TO_LABEL[index]: per_class_correct[index].item() / max(per_class_total[index].item(), 1)
        for index in range(NUM_CLASSES)
    }
    return {
        "loss": total_loss / total_nodes,
        "acc": correct / total_nodes,
        "safety_mae": safety_error / total_nodes,
        "anomaly_mae": anomaly_error / total_nodes,
        "per_class": per_class,
    }


def checkpoint_payload(model, config, epoch, val_metrics):
    return {
        "model_state_dict": model.state_dict(),
        "num_features": NUM_FEATURES,
        "num_classes": NUM_CLASSES,
        "hidden_dim": config["hidden_dim"],
        "num_heads": config["num_heads"],
        "num_layers": config["num_layers"],
        "dropout": config["dropout"],
        "epoch": epoch,
        "val_metrics": val_metrics,
        "config": config,
    }


def train(config, train_graphs, val_graphs, checkpoint_path=CHECKPOINT_PATH):
    device = choose_device(config["device"])
    train_loader = DataLoader(train_graphs, batch_size=config["batch_size"], shuffle=True)
    val_loader = DataLoader(val_graphs, batch_size=config["batch_size"], shuffle=False)
    weights = class_weights(train_graphs).to(device)
    model = GATModel(
        num_features=NUM_FEATURES,
        hidden_dim=config["hidden_dim"],
        num_classes=NUM_CLASSES,
        num_heads=config["num_heads"],
        num_layers=config["num_layers"],
        dropout=config["dropout"],
    ).to(device)
    start_epoch = 1
    resume_checkpoint = None
    if config.get("resume"):
        resume_checkpoint = torch.load(config["resume"], map_location=device, weights_only=True)
        model.load_state_dict(resume_checkpoint["model_state_dict"])
        start_epoch = resume_checkpoint.get("epoch", 0) + 1
    optimizer = torch.optim.AdamW(model.parameters(), lr=config["lr"], weight_decay=config["weight_decay"])
    scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=50, T_mult=2)
    history = []
    best_metrics = resume_checkpoint.get("val_metrics", {}) if resume_checkpoint else {}
    best_acc = best_metrics.get("acc", -1.0)
    best_loss = best_metrics.get("loss", float("inf"))
    best_per_class = best_metrics.get("per_class", {})
    best_meets_class_gate = bool(best_per_class) and min(best_per_class.values()) >= 0.85
    epochs_without_improvement = 0
    if start_epoch > 1:
        scheduler.step(start_epoch - 1)
    checkpoint_path.parent.mkdir(parents=True, exist_ok=True)
    print(f"device={device} train_graphs={len(train_graphs)} val_graphs={len(val_graphs)}")
    print(f"features={NUM_FEATURES} hidden={config['hidden_dim']} heads={config['num_heads']} layers={config['num_layers']}")
    for epoch in range(start_epoch, config["epochs"] + 1):
        started = time.perf_counter()
        model.train()
        train_loss = 0.0
        train_nodes = 0
        train_correct = 0
        for batch_index, source_batch in enumerate(train_loader):
            batch = augment_batch(source_batch.to(device))
            optimizer.zero_grad(set_to_none=True)
            loss, logits, _, _ = loss_components(model, batch, weights, config.get("w_class", 3.0))
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()
            scheduler.step(epoch - 1 + (batch_index + 1) / len(train_loader))
            nodes = batch.y.numel()
            train_loss += loss.item() * nodes
            train_nodes += nodes
            train_correct += (logits.argmax(dim=1) == batch.y).sum().item()
        val_metrics = evaluate_loader(model, val_loader, device, weights, config.get("w_class", 3.0))
        train_loss /= train_nodes
        train_acc = train_correct / train_nodes
        lr = optimizer.param_groups[0]["lr"]
        record = {
            "epoch": epoch,
            "lr": lr,
            "train_loss": train_loss,
            "train_acc": train_acc,
            "val_loss": val_metrics["loss"],
            "val_acc": val_metrics["acc"],
            "val_safety_mae": val_metrics["safety_mae"],
            "val_anomaly_mae": val_metrics["anomaly_mae"],
            "seconds": time.perf_counter() - started,
            "per_class": val_metrics["per_class"],
        }
        history.append(record)
        worst = sorted(val_metrics["per_class"].items(), key=lambda item: item[1])[:5]
        print(f"Epoch {epoch}/{config['epochs']}  lr={lr:.6f}")
        print(f"  train_loss={train_loss:.4f}  train_acc={train_acc:.4f}")
        print(f"  val_loss={val_metrics['loss']:.4f}  val_acc={val_metrics['acc']:.4f}")
        print(f"  val_safety_mae={val_metrics['safety_mae']:.4f}  val_anomaly_mae={val_metrics['anomaly_mae']:.4f}")
        print(f"  worst_classes={dict(worst)}  seconds={record['seconds']:.2f}", flush=True)
        meets_class_gate = min(val_metrics["per_class"].values()) >= 0.85
        improved = (
            meets_class_gate and not best_meets_class_gate
            or meets_class_gate == best_meets_class_gate and (
                val_metrics["acc"] > best_acc
                or val_metrics["acc"] == best_acc and val_metrics["loss"] < best_loss
            )
        )
        if improved:
            best_acc = val_metrics["acc"]
            best_loss = val_metrics["loss"]
            best_meets_class_gate = meets_class_gate
            epochs_without_improvement = 0
            cpu_model = copy.deepcopy(model).cpu()
            torch.save(checkpoint_payload(cpu_model, config, epoch, val_metrics), checkpoint_path)
        else:
            epochs_without_improvement += 1
        with METRICS_PATH.open("w") as metrics_file:
            json.dump(history, metrics_file, indent=2)
        if epochs_without_improvement >= config["patience"]:
            print(f"Early stopping after {config['patience']} epochs without improvement")
            break
    best_checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=True)
    print(f"BEST VAL ACCURACY: {best_checkpoint['val_metrics']['acc']:.4f} at epoch {best_checkpoint['epoch']}")
    return best_checkpoint, history


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--graphs", type=int, default=10_000)
    parser.add_argument("--epochs", type=int, default=500)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--hidden-dim", type=int, default=128)
    parser.add_argument("--num-heads", type=int, default=8)
    parser.add_argument("--num-layers", type=int, default=3)
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--lr", type=float, default=0.001)
    parser.add_argument("--weight-decay", type=float, default=0.001)
    parser.add_argument("--w-class", type=float, default=3.0)
    parser.add_argument("--patience", type=int, default=100)
    parser.add_argument("--device", choices=("auto", "cpu", "mps"), default="auto")
    parser.add_argument("--train-limit", type=int)
    parser.add_argument("--val-limit", type=int)
    parser.add_argument("--checkpoint", type=Path, default=CHECKPOINT_PATH)
    parser.add_argument("--resume", type=Path)
    return parser.parse_args()


def main():
    args = parse_args()
    random.seed(42)
    torch.manual_seed(42)
    if args.generate or not all((DATA_DIR / f"{split}.pt").exists() for split in ("train", "val", "test")):
        save_datasets(args.graphs)
    train_graphs = load_graphs(DATA_DIR / "train.pt")
    val_graphs = load_graphs(DATA_DIR / "val.pt")
    if args.train_limit:
        train_graphs = train_graphs[:args.train_limit]
    if args.val_limit:
        val_graphs = val_graphs[:args.val_limit]
    config = {
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "hidden_dim": args.hidden_dim,
        "num_heads": args.num_heads,
        "num_layers": args.num_layers,
        "dropout": args.dropout,
        "lr": args.lr,
        "weight_decay": args.weight_decay,
        "w_class": args.w_class,
        "patience": args.patience,
        "device": args.device,
        "resume": str(args.resume) if args.resume else None,
    }
    train(config, train_graphs, val_graphs, args.checkpoint)


if __name__ == "__main__":
    main()
