name: Question
description: Ask a question about X-MaC
title: "[question] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you tried so far? What docs have you read?
