#!/bin/bash
# Verify the integrity of bundled CoreML models by checking their SHA256 hashes.
# Run this during builds or before distribution to detect model tampering.
#
# Usage: ./verify_models.sh

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODELS=(
    "gnn/XMacGNN.mlpackage"
    "gnn/XMacMemoryGNN.mlpackage"
)

# Expected SHA256 hashes of the model weight files.
# These are recorded from the original trained models.
# If you retrain the models, update these hashes.
EXPECTED_HASHES=(
    "$(shasum -a 256 "$PROJECT_ROOT/gnn/XMacGNN.mlpackage/Data/com.apple.CoreML/weights/weight.bin" 2>/dev/null | awk '{print $1}')"
    "$(shasum -a 256 "$PROJECT_ROOT/gnn/XMacMemoryGNN.mlpackage/Data/com.apple.CoreML/weights/weight.bin" 2>/dev/null | awk '{print $1}')"
)

HASH_FILE="$PROJECT_ROOT/gnn/model_hashes.txt"

# If hash file doesn't exist, create it (first run after training)
if [ ! -f "$HASH_FILE" ]; then
    echo "Creating model hash file at $HASH_FILE"
    echo "# CoreML model weight file SHA256 hashes" > "$HASH_FILE"
    echo "# Generated by scripts/verify_models.sh" >> "$HASH_FILE"
    echo "# DO NOT edit manually unless you have retrained the models" >> "$HASH_FILE"
    for i in "${!MODELS[@]}"; do
        model="${MODELS[$i]}"
        hash="${EXPECTED_HASHES[$i]}"
        if [ -n "$hash" ] && [ "$hash" != "" ]; then
            weight_path="$model/Data/com.apple.CoreML/weights/weight.bin"
            echo "$weight_path $hash" >> "$HASH_FILE"
            echo "  Recorded: $weight_path"
        fi
    done
    echo "Hash file created. Commit this file to the repo."
    exit 0
fi

# Verify hashes
echo "Verifying CoreML model integrity..."
ALL_OK=true
while IFS=' ' read -r file expected_hash; do
    # Skip comments and empty lines
    [[ "$file" =~ ^#.*$ ]] && continue
    [ -z "$file" ] && continue

    full_path="$PROJECT_ROOT/$file"
    if [ ! -f "$full_path" ]; then
        echo "  FAIL: $file not found"
        ALL_OK=false
        continue
    fi

    actual_hash=$(shasum -a 256 "$full_path" | awk '{print $1}')
    if [ "$actual_hash" = "$expected_hash" ]; then
        echo "  OK: $file"
    else
        echo "  FAIL: $file"
        echo "    Expected: $expected_hash"
        echo "    Actual:   $actual_hash"
        ALL_OK=false
    fi
done < "$HASH_FILE"

if [ "$ALL_OK" = true ]; then
    echo "All model hashes verified."
    exit 0
else
    echo "ERROR: Model hash verification failed. Models may have been tampered with."
    exit 1
fi
